NS_CONSUMER_KEY=""

NS_CONSUMER_SECRET=""

NS_TOKEN_ID=""
NS_TOKEN_SECRET=""

NS_ACCOUNT_ID="1234567"


NS_RESTLET_URL = "https://1234567.restlets.api.netsuite.com/app/site/hosting/restlet.nl"
NS_SCRIPT_ID = "customscript_restlet_saved_search"
NS_DEPLOY_ID = "customdeploy_restlet_saved_search"